In [76]:
import pymysql
import pandas as pd

conn = pymysql.connect(
    host='198.199.81.151',
    port=3306,
    user='zhanyl',
    passwd='qwerty',
    db='test',
    charset='utf8mb4')
print("connection successful!")

connection successful!

In [77]:
 df2 = pd.read_sql_query(
    "select FullNameRu from Minjust2018 limit 10",conn)
    
def find_related_companies_by_founders(companies_df, db_conn):
    founders=companies_df.iloc[:,1]
    founders_list=founders.values.toList()
    companiesList=list(map(find_companies_by_founders_string, founders_list)) 
    return companiesList

def find_companies_by_founders_string (founders_string,dbconn):
    listFounders= founders_string.split(',')
    companiesList=list(map(find_companiesByFounder,founderList))
    return companiesList

def find_companiesByFounder (founder, db_conn):
    df2 = pd.read_sql_query(
    "select FullNameRu from Minjust2018 where Founders like '%" + founder + "%' limit 10", db_conn)
    return df2

print(find_related_companies_by_founders(df2,conn))

IndexError: single positional indexer is out-of-bounds

In [71]:
def multiple2(n):
    return n*2
number_list= [1,5,4,9]
number_list_multiple= list(map(multiple2,number_list ))
print(number_list_multiple)

[2, 10, 8, 18]

In [69]:
print(plus2(9))

11

In [68]:
def plus2(n):
    return(n+2)

In [9]:
df = pd.read_sql_query(
    "SELECT * FROM Minjust2018 LIMIT 0, 10",
    conn)
df.tail(10)

,id,Date,links_id,FullNameKy,FullNameRu,ShortNameKy,ShortNameRu,OrgForm,ForeignFounders,RegNumber,...,RegMethod,OwnershipForm,HeadName,MainActivity,ActivityCode,PhysFoundersNum,JurFoundersNum,TotalFoundersNum,Founders,Notes
0,1,2018-03-04 18:45:04,2,"""Казкоммерцбанк Кыргызстан"" ачык акционердик к...",Жалал-Абадский филиал открытого акционерного о...,"""Казкоммерцбанк Кыргызстан"" ААК ЖАФ","ЖАФ ОАО ""Казкоммерцбанк Кыргызстан""",Филиал,нет,107596-3303-Ф-л,...,None,Частная,Орозбаев Талантбек Жалилович,Предоставление кредитов,None,0,1,None,None,None
1,2,2018-06-03 13:13:05,1,"У-е "" Центр спортивной медицины и реаблитации ...","У-е "" Центр спортивной медицины и реаблитации ...","У-е "" Центр спортивной медицины и реаблитации ...","У-е "" Центр спортивной медицины и реаблитации ...",Учреждение,нет,101128-3310-У-е,...,None,Муниципальная,Школьников Николай Яковлевич,None,None,None,1,None,Мэрия города Ош,None
2,3,2018-06-03 13:13:12,2,"""Казкоммерцбанк Кыргызстан"" ачык акционердик к...",Жалал-Абадский филиал открытого акционерного о...,"""Казкоммерцбанк Кыргызстан"" ААК ЖАФ","ЖАФ ОАО ""Казкоммерцбанк Кыргызстан""",Филиал,нет,107596-3303-Ф-л,...,None,Частная,Орозбаев Талантбек Жалилович,Предоставление кредитов,None,0,1,None,,None
3,4,2018-06-03 13:13:14,3,"""Алтынбек-Эркинбек"" дыйкан чарбасы","Крестиьянское хозяйство ""Алтынбек-Эркинбек""",None,None,Крестьянское (фермерское) хозяйство,нет,102342-3306-КХ,...,None,Частная,Турдуев Марипбай Маманович,None,None,1,None,None,Турдуев Марипбай Маманович,None
4,5,2018-06-03 13:13:16,4,"ООО ""Турандот""","ООО ""Турандот""","ООО ""Турандот""","ООО ""Турандот""",Общество с ограниченной ответственностью,нет,100264-3310-ООО,...,None,Частная,Кадырбекова Гулназ Сагындыковна,None,None,1,None,None,Кадырбекова Гулназ Сагындыкова,None
5,6,2018-06-03 13:13:18,5,"""Кызылтоо-Озгон"" коомдук фонду","Общественный фонд ""Кызылтоо-Озгон""","""Кызылтоо-Озгон"" КФ","ОФ ""Кызылтоо-Озгон""",Общественный фонд,нет,102359-3306-ОФ,...,None,Частная,Тешебаев Назирбай,благотворительность,None,1,0,None,Тешебаев Назирбай,None
6,7,2018-06-03 13:13:19,6,"ОФ ""TOEFL CENTER"" (Тоэфл центр)","ОФ ""TOEFL CENTER"" (Тоэфл центр)",None,None,Общественный фонд,нет,53413-3301-ОФ,...,None,Частная,Кулева Мария Тимофеевна,None,None,2,0,None,"Кулева Мария Тимофеевна, Рындина Светлана Серг...",None
7,8,2018-06-03 13:13:20,7,"""Кубанычбек Ата Кубансын"" айыл чарба кооперативи","Сельскохозяйственный кооператив ""Кубанычбек Ат...",None,None,Коммерческий кооператив,нет,100327-3307-КК,...,None,Частная,Балапанов Талант Кубанычбекович,None,None,7,1,None,"Балапанов Талант Кубанычбекович, Балапанов Куб...",None
8,9,2018-06-03 13:13:21,8,"""Вербена"" Турак жай менчик ээлеринин шериктиги","Товарищество собственников жилья ""Вербена""","""Вербена"" ТЖМЭШ","ТСЖ""Вербена""",Ассоциация водопользователей,нет,120546-3301-АВ,...,None,Частная,Камкина Наталья Владимировна,None,None,38,0,None,согласно представленного списка,None
9,10,2018-06-03 13:13:22,9,"""Лайф Плюс"" коомдук фонду","Обшественный фонд ""Лайф Плюс""","""Лайф Плюс"" КФ","ОФ ""Лайф Плюс""",Общественный фонд,нет,104986-3310-ОФ,...,None,Частная,Галиева Алтынай Душаевна,благотворительная,None,1,0,None,Галиева Алтынай Душаевна,None

In [10]:
conn.close()
print("connection closed")

connection closed

In [6]:
df = pd.read_sql_query(
    "select Minjust2018.HeadName, Minjust2018.Founders, Minjust2018.FullNameRu, persons.fullName, persons.inn from persons join Minjust2018 on persons.fullName LIKE  CONCAT('%', Minjust2018.HeadName, '%') or persons.fullName LIKE  CONCAT('%', Minjust2018.Founders,'%') WHERE (persons.inn REGEXP '([1-2][0-9][0-9][0-9][0-9])([1][9][9][7-9])|([2][0][0][0-9])*') limit 10",
    conn)
df.tail(10)

,HeadName,Founders,FullNameRu,fullName,inn
0,Орозбаев Талантбек Жалилович,,Жалал-Абадский филиал открытого акционерного о...,Джолдошбекова Айсезим Таалайбековна,12112199401001
1,None,,Сельскохозяйственный семеноводческий кооперати...,Джолдошбекова Айсезим Таалайбековна,12112199401001
2,None,,"Объединение крестьянских хозяйств ""Кой-Таш""",Джолдошбекова Айсезим Таалайбековна,12112199401001
3,Чормопов Мелис Бакасович,,"Малое предприятие Фирма ""Квадрига""",Джолдошбекова Айсезим Таалайбековна,12112199401001
4,Жунусалиев Алтынбек Аданбекович,,"АОЗТ ""7Ж"" (уведомление о смене руков. от 28.11...",Джолдошбекова Айсезим Таалайбековна,12112199401001
5,Решетникова Наталья Николаевна,,"ОсОО ""Кубаныч""",Джолдошбекова Айсезим Таалайбековна,12112199401001
6,Аллашукурова Ирина Николаевна,,"Кыргызско-Российское совместное предприятие ""А...",Джолдошбекова Айсезим Таалайбековна,12112199401001
7,М.А. Шопоков,,"Ассоциация крестьянских хозяйств ""Шалта"" (юр. ...",Джолдошбекова Айсезим Таалайбековна,12112199401001
8,Попов Владимир Михайлович,,"Закрытое акционерное общество ""ТЕХКОМ""",Джолдошбекова Айсезим Таалайбековна,12112199401001
9,Ибраимова Сабыркуль Абдурасуловна,,Ысык-Атинское районо.,Джолдошбекова Айсезим Таалайбековна,12112199401001

In [16]:
df = pd.read_sql_query(
    "select Minjust2018.HeadName, Minjust2018.Founders, Minjust2018.FullNameRu, persons.fullName, persons.inn from persons join Minjust2018 on persons.fullName LIKE CONCAT('%', Minjust2018.HeadName, '%') or persons.fullName LIKE CONCAT('%', Minjust2018.Founders,'%') WHERE (Year(CURDATE())- SUBSTRING(persons.inn, 6, 4)<21 And (persons.inn like '1%' or persons.inn like '2%')) limit 10", conn)
df.tail(10)

,HeadName,Founders,FullNameRu,fullName,inn
0,Орозбаев Талантбек Жалилович,,Жалал-Абадский филиал открытого акционерного о...,Иманалиева Айсулуу Таалайбековна,11412199801024
1,None,,Сельскохозяйственный семеноводческий кооперати...,Иманалиева Айсулуу Таалайбековна,11412199801024
2,None,,"Объединение крестьянских хозяйств ""Кой-Таш""",Иманалиева Айсулуу Таалайбековна,11412199801024
3,Чормопов Мелис Бакасович,,"Малое предприятие Фирма ""Квадрига""",Иманалиева Айсулуу Таалайбековна,11412199801024
4,Жунусалиев Алтынбек Аданбекович,,"АОЗТ ""7Ж"" (уведомление о смене руков. от 28.11...",Иманалиева Айсулуу Таалайбековна,11412199801024
5,Решетникова Наталья Николаевна,,"ОсОО ""Кубаныч""",Иманалиева Айсулуу Таалайбековна,11412199801024
6,Аллашукурова Ирина Николаевна,,"Кыргызско-Российское совместное предприятие ""А...",Иманалиева Айсулуу Таалайбековна,11412199801024
7,М.А. Шопоков,,"Ассоциация крестьянских хозяйств ""Шалта"" (юр. ...",Иманалиева Айсулуу Таалайбековна,11412199801024
8,Попов Владимир Михайлович,,"Закрытое акционерное общество ""ТЕХКОМ""",Иманалиева Айсулуу Таалайбековна,11412199801024
9,Ибраимова Сабыркуль Абдурасуловна,,Ысык-Атинское районо.,Иманалиева Айсулуу Таалайбековна,11412199801024

In [36]:
df = pd.read_sql_query(
    "select Minjust2018.HeadName, Minjust2018.Founders, Minjust2018.FullNameRu, persons.fullName, persons.inn from persons join Minjust2018 on persons.fullName LIKE CONCAT('%', Minjust2018.HeadName, '%') or persons.fullName LIKE CONCAT('%', Minjust2018.Founders,'%') WHERE (Year(CURDATE())- SUBSTRING(persons.inn, 6, 4)<21 And (persons.inn like '1%' or persons.inn like '2%')) limit 10", conn)
df.iloc[2,3]

'Иманалиева Айсулуу Таалайбековна'

In [60]:
df = pd.read_sql_query(
    "select Founders, FullNameRu from Minjust2018 limit 100", conn)
df.iloc[7,0]

'Балапанов Талант Кубанычбекович, Балапанов Кубанычбек Кукумбаевич, Бейшеналиева Алиакул, Кошалиев Омор Касымович, Балапанов Бакыт Кубанычбекович, Турсалиева Гульбар Ергешовна, Султанова Кылым Джорупбековна'

In [67]:
df = pd.read_sql_query(
    "select Founders, FullNameRu from Minjust2018 limit 10", conn)
founders=df.iloc[7,0]
founders_list = founders.split(',')
a=founders_list[1]

df2 = find_companiesByFounder(a,conn)
df2.tail(10)

                                          FullNameRu
0  Сельскохозяйственный кооператив "Кубанычбек Ат...

Вывод людей младше 21, имеющих бизнес в КР

In [22]:
df = pd.read_sql_query(
    "SELECT declaration.positn, declaration.first_name,declaration.middle_name,declaration.last_name, declaration.income_sum, bulgarien_prop.adress as 'адрес в Болгарии' from declaration join bulgarien_prop on bulgarien_prop.name_Ru like CONCAT('%', declaration.last_name,'%') where bulgarien_prop.property LIKE 'YES' limit 100", conn)
df.tail(10)

,positn,first_name,middle_name,last_name,income_sum,адрес в Болгарии
28,Эксперт,Асель,Омурбековна,Бейшеналиева,596642,( Физическо лице - субект на Булстат) адрес:(с...
29,Эксперт,Асель,Омурбековна,Бейшеналиева,596642,( Физическо лице - субект на Булстат) адрес:(с...
30,Заведующий сектором,Жетиген,Жокинович,Бакиров,622686,
31,Заведующий сектором,Жетиген,Жокинович,Бакиров,622686,( Физическо лице - субект на Булстат) адрес:(с...
32,Инспектор,Амангелди,Сайдимаматович,Бакиров,919689,
33,Инспектор,Амангелди,Сайдимаматович,Бакиров,919689,( Физическо лице - субект на Булстат) адрес:(с...
34,Руководитель аппарата,Кайратбек,Муратбекович,Асанов,342536,( Физическо лице - субект на Булстат) адрес:(с...
35,Мэр,Болот,Саякович,Бакиров,368328,
36,Мэр,Болот,Саякович,Бакиров,368328,( Физическо лице - субект на Булстат) адрес:(с...
37,Пресс-секретарь премьер-министра,Бакытбек,Сарбагышович,Асанов,615570,( Физическо лице - субект на Булстат) адрес:(с...

Список людей, занимающих должность в правительстве, имеющих имущество в Болгарии